### ISSUE TITLE
Resolve nvim-compe input lag on large file?

### ISSUE THREAD

**Issue by vpeopleonatank** [Shatur95/neovim-config#1]
I saw your issue on nvim-compe about this problem. Do you have some workaround to solve It?

**Comment by Shatur** [comment]
Hi! You could use [the following](https://github.com/hrsh7th/nvim-compe/issues/321#issuecomment-814789105).
Try to ping author in the issue. Maybe we could just disable completion via option if file is bigger then specified number of lines.

**Comment by vpeopleonatank** [comment]
Thank for your help
